# Site settings
# title: "Wiki"
logo: "/title-logo.png"
remote_theme: pmarsceill/just-the-docs
description: "Stockholm Changeling LARP Wiki"
permalink: pretty
heading_anchors: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Header
search_enabled: true
aux_links_new_tab: true
# aux_links:
#   "Homepage":
#    - "https://www..."

# Footer
footer_content: ""
last_edit_timestamp: true # Page must have last_modified_date defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Google analytics tracking
ga_tracking: UA-197568842-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Optimisations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false