# Site settings
title: "Wiki"
logo: "/title-logo.png"
remote_theme: pmarsceill/just-the-docs
description: "Stockholm Changeling LARP Wiki"
permalink: pretty
heading_anchors: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Header
search_enabled: true
aux_links_new_tab: true
# aux_links:
#   "Homepage":
#    - "https://www..."

# Footer
footer_content: "Community content distributed by <a href=\"https://creativecommons.org/licenses/by/4.0/legalcode\">CC BY 4.0</a>. Content copyrighted by White Wolf Entertainment AB and By Night studios LLC, remains copyrighted to the respective parties. No infringement is intended. Spotted a mistake? Report <a href=\"https://github.com/siliconwitch/changelingsthlm/issues\">issues here</a>. Want to contribute to this wiki? Engage in the <a href=\"https://github.com/siliconwitch/changelingsthlm/discussions\">discussion here</a>."
last_edit_timestamp: true # Page must have last_modified_date defined in the front matter
last_edit_time_format: "%b %e %Y"

# Google analytics tracking
ga_tracking: UA-197568842-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false